### ISSUE TITLE
Autogenerate html files from markdown files (on github)

### ISSUE THREAD

**Issue by agrez** [fedberry/fedberry-release#1]
I have manually generated these files for the moment but I would like to add support in the spec to auto generate the *.html files at build time.

**Comment by agrez** [comment]
[root@r3d3 default]# dnf provides '*/bin/markdown'
Last metadata expiration check performed 0:03:57 ago on Tue Feb  2 09:38:11 2016.
discount-2.1.8-1.fc22.x86_64 : A command-line utility for converting Markdown files into HTML
Repo        : fedora

**Comment by mrjoshuap** [comment]
is this generally for all spec files or for specific repos?

**Comment by Gormartsen** [comment]
@agrez where do we use this html files?

**Comment by Gormartsen** [comment]
It's for man pages right?

**Comment by agrez** [comment]
I was just thinking of using it in repos that contain any markdown (MD) files. Since github encourages MD usage, we might end up with quite a few. Thanks for implementing this!
