### ISSUE TITLE
Plymouth not showing at all

### ISSUE THREAD

**Issue by 3esmit** [fedberry/fedberry-release#2]
I enabled plymouth and boot.log says it started and later stopped, but nothing shows at screen. 
I am trying to enable plymouth to show a loading process at startup. 
Also, I was unable to change the loglevel of boot messages. 

How do I enable this in FedBerry 23?

**Comment by agrez** [comment]
To get graphical plymouth (ie. a loading progress screen) working in Fedora we need to boot using an initrd. Presently (for various reasons) FedBerry boots without using an initrd, so there is no support for graphical plymouth at this time. There may be workarounds but I haven't investigated these as yet.

At some point in the future we might be moving to using uboot. This will use an initrd for booting which will solve the issue.

**Comment by agrez** [comment]
I just had thought as I go to close this bug and I may have misunderstood you (sorry). Are you using the mini release? If so, it doesn't have plymouth installed at all (unlike minimal & XFCE releases), so you will have to install manually. Eg:
`dnf install plymouth`
